Repository opensearch-project/opensearch-benchmark, pull requests merged in 2024-02, with the labels that each got.

#454 Emit a more informative error message if git is not installed at startup
  it/__init__.py
  osbenchmark/utils/git.py
  tests/utils/git_test.py
Labels: Low Priority

#448 Surface Workload and Jinja Template Errors to Console and Provide Common Solutions
  osbenchmark/workload/loader.py
Labels: Low Priority

#450 Added a new metric: Client Processing Time
  osbenchmark/client.py
  osbenchmark/metrics.py
  osbenchmark/worker_coordinator/runner.py
  osbenchmark/worker_coordinator/worker_coordinator.py
  tests/worker_coordinator/runner_test.py
  tests/worker_coordinator/worker_coordinator_test.py
Labels: High Priority

#452 Move data set loading outside constructor
  osbenchmark/utils/dataset.py
  osbenchmark/workload/params.py
  tests/workload/params_test.py
Labels: Medium Priority

#464 Make neighbor's dataset path as optional
  osbenchmark/workload/params.py
  tests/utils/dataset_helper.py
  tests/workload/params_test.py
Labels: High Priority
